# @package __global__

  device: cuda
  vectorization: multiprocessing

  train:
    num_workers: 24 # num cores
    minibatch_size: 4096
    async_factor: 2
    zero_copy: True
    total_timesteps: 7e9
    checkpoint_interval: 2000

