cmd: ???
experiment: ???
data_dir: ./train_dir

dashboard: true

seed: 1
torch_deterministic: true

defaults:
  - framework: pufferlib
  - agent: tuned
  - env: mettagrid/a20_b4_40x40
  - hardware: macbook
  - wandb: wandb
  - sweep: sweep
  - eval: eval

