defaults:
  - sweep

parameters:
  batch_size:
    search_center: 128
    min: 128
    max: 1024
  minibatch_size:
    search_center: 128
    min: 128
    max: 1024
  forward_pass_minibatch_target_size:
    space: log
    is_pow2: true
    search_center: 2
    min: 1
    max: 4
  bptt_horizon:
    search_center: 8
    max: 8
  total_timesteps:
    search_center: 1e5
    min: 1e5
    max: 1e8



