metric: episode/reward.mean

parameters:
  framework:
    pufferlib:
      train:
        learning_rate:
          space: log
          search_center: 2.5e-4
          min: 1e-5
          max: 1e-1
        gamma:
          space: logit
          search_center: 0.95
          min: 0.0
          max: 1.0
        gae_lambda:
          space: logit
          search_center: 0.90
          min: 0.0
          max: 1.0
        update_epochs:
          space: linear
          is_int: true
          search_center: 1
          min: 1
          max: 16
        clip_coef:
          space: logit
          search_center: 0.1
          min: 0.0
          max: 1.0
        vf_coef:
          space: logit
          search_center: 0.5
          min: 0.0
          max: 1.0
        vf_clip_coef:
          space: logit
          search_center: 0.1
          min: 0.0
          max: 1.0
        max_grad_norm:
          space: linear
          search_center: 0.5
          min: 0.0
          max: 1.0
        ent_coef:
          space: log
          search_center: 0.01
          min: 1e-5
          max: 1e-1
        batch_size:
          space: pow2
          search_center: 262144
          min: 65536
          max: 524288
        minibatch_size:
          space: pow2
          search_center: 4096
          min: 1024
          max: 32768
        num_minibatches:
          space: linear
          search_center: 1
          is_int: true
          min: 1
          max: 8
        forward_pass_minibatch_target_size:
          space: pow2
          search_center: 4096
          min: 1024
          max: 32768
        # async_factor:
        #   space: linear
        #   search_center: 2
        #   is_int: true
        #   min: 1
        #   max: 8
        bptt_horizon:
          space: pow2
          search_center: 8
          min: 1
          max: 256
        total_timesteps:
          space: log
          search_center: 1e6
          min: 1e6
          max: 1e13
          is_int: true



  agent:
    observation_encoders:
      grid_obs:
        label_dim:
          space: linear
          search_center: 4
          is_int: true
          min: 2
          max: 16
        output_dim:
          space: pow2
          search_center: 128
          min: 32
          max: 512
        layers:
          space: linear
          search_center: 2
          is_int: true
          min: 1
          max: 6
        normalize_features:
          space: linear
          search_center: 0
          is_int: true
          min: 0
          max: 1
    fc:
      layers:
        space: linear
        search_center: 1
        is_int: true
        min: 1
        max: 4
      output_dim:
        space: pow2
        search_center: 128
        min: 32
        max: 512

    core:
      rnn_num_layers:
        space: linear
        search_center: 1
        is_int: true
        min: 1
        max: 4
      rnn_size:
        space: pow2
        search_center: 128
        min: 32
        max: 512
